### ISSUE TITLE
Stable Matching Algorithm

### ISSUE THREAD

**Issue by Preetesh21** [rituburman/hacktoberfest2020#146]
Stable Matching Algorithm in C++ language.

**Comment by Ayan1089** [comment]
Can I work on this issue?

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
