### ISSUE TITLE
Largest Contiguous Subarray

### ISSUE THREAD

**Issue by ashishsalunkhe** [rituburman/hacktoberfest2020#226]
[largestcontiguoussubarray.txt](https://github.com/rituburman/hacktoberfest2020/files/5464556/largestcontiguoussubarray.txt)

**Comment by navjotdadwal** [comment]
sir can you please assign this issue to me i am current rated 5 star at codechef with rating of 2153 and rated expert at codeforces with rating of 1776 and i use cpp language for competitive programming and can resolve this issue
