### ISSUE TITLE
Leetcode Problem: 208. Implement Trie (Prefix Tree)

### ISSUE THREAD

**Issue by Aashna-Agrawal** [rituburman/hacktoberfest2020#75]
Solution for the leetcode problem 208: Implement Trie (Prefix Tree)

**Comment by Aashna-Agrawal** [comment]
Please assign the above issue to me

**Comment by satyambup** [comment]
Hello!
please may you assign this to me

**Comment by Aashna-Agrawal** [comment]
Resolved.
Create Implement Trie (Prefix Tree) #76
